# KL Metric for Quantifying Summary Loss

In [9]:
from dotenv import load_dotenv
load_dotenv()

True

In [10]:
import os
os.environ['HF_ROOT']

'~/scratch/jennifer/hf'

In [11]:
import os
from pathlib import Path

hf_root = Path(os.environ['HF_ROOT'])
hf_root.mkdir(parents=True, exist_ok=True)
(hf_root / "transformers").mkdir(parents=True, exist_ok=True)
(hf_root / "datasets").mkdir(parents=True, exist_ok=True)

os.environ["HF_HOME"] = str(hf_root)
os.environ["TRANSFORMERS_CACHE"] = str(hf_root / "transformers")
os.environ["HF_DATASETS_CACHE"] = str(hf_root / "datasets")

hf_root

PosixPath('~/scratch/jennifer/hf')

In [12]:
os.environ["HF_HOME"]

'~/scratch/jennifer/hf'

In [13]:
from datasets import load_dataset

# # Login using e.g. `huggingface-cli login` to access this dataset
# ot_ds = load_dataset("open-thoughts/OpenThoughts3-1.2M")

In [14]:
# om_ds = load_dataset("microsoft/OpenMementos")
om_ds = load_dataset("microsoft/OpenMementos", "full", split="train")

Downloading data: 100%|██████████| 39/39 [05:32<00:00,  8.53s/files]
Generating train split: 100%|██████████| 228557/228557 [01:47<00:00, 2126.35 examples/s]

In [15]:
# ot_ds

In [16]:
om_ds

Dataset({
    features: ['problem', 'response', 'domain', 'source', 'difficulty', 'sentences', 'blocks', 'block_summaries'],
    num_rows: 228557
})

In [17]:
# ot_ds['train'][0]['conversations']

In [18]:
om_ds[0]['problem']

"The problem over here introduces an new type of strings: if you split the string into equal halfs and swap the pairs, it produces the same output as sorting the string. We call that a half-sort.\nGiven a purely ASCII string, check if the string is in a half-sort.\nAn example of a half-sort string\nThe string node is a half-sort string, because if you sort by codepoints (note that the codepoints are in decimal, not binary):\nn 110\no 111\nd 100\ne 101\n\nThat gets turned into:\nd 100\ne 101\nn 110\no 111\n\nYou'll see that the node to deno conversion is exactly moving the right half to the left position.\nSpecification\n\nFor odd-length strings, splitting should make the first half longer.\nSorting a string means sorting the string based on the codepoints of the characters.\n\nReference program & test cases\nHere is the reference program I made for checking my test cases.\nnode -> True\nrum  -> True\naaa  -> True\n\ndeno -> False\nrim  -> False\n\n"

In [19]:
om_ds[0]['sentences']

["Okay, so I need to figure out how to determine if a given string is a half-sort. Hmm, let's start by understanding the problem again. The half-sort is when if you split the string into two equal halves (with the first half being longer if the length is odd), then swap those two halves, the result should be the same as sorting the original string. Oh right, and splitting for odd-length means the first half is longer.",
 'Let me rephrase the example given. Take the string "node".',
 'The original characters are n, o, d, e. When sorted by their ASCII codes, they become d, e, n, o. Which is "deno".',
 'Now, splitting "node" into two halves: since it\'s 4 characters, each half is 2. The first half is \'no\' and the second is \'de\'.',
 "Swapping gives 'deno', which matches the sorted version. So that's why it's a half-sort.",
 'The task is to write a function that checks if a given string satisfies this condition.',
 "So the steps I need to do are:\n1. Check the length of the string. If it's 0 or 1, maybe it's trivially half-sort?",
 'Wait, if length is 1, then splitting into halves would just have the first half as the entire string and the second as empty?',
 "Or maybe according to the specs, for odd length, first half is longer. So length 1 would be first half (1 char), second half none?\nSo swapping would mean moving the second (empty) to front and first part to end, but that would be the same?\nHmm, but let's see. Maybe for length 1, the split is first half (1), second half (0).",
 'Swapping them gives the original string. Then the sorted version must also be the original. So only if the string is already sorted, which a single character is. So for length 1, it would return True.',
 '2. For the general case:\n- Split the string into two parts: left and right. The split point is at (length + 1) // 2 for the first part. Because for odd length, first part is longer by one.',
 'Wait, for example, when the string length is 5, split at (5+1)/2 = 3, so first part is 3, second 2. Correct. So for n even length like 4, the split is (4 +1)/2?',
 'Wait wait, 4 is even, so (4 +1)//2 would be 2.5 rounded down?\nWait, (4+1) is 5 divided by 2 is 2.5. Using integer division, 5//2 is 2. So split at 2 and 2. That makes sense.\nWait no. Wait, (length +1 )//2 gives the split point for the first part. So for length 4, (4+1)//2 is 2.5?',
 "No, (4+1) is 5 divided by 2, integer division is 2. Wait, 5 divided by 2 is 2 with remainder 1, so yes, 2. So the first part is 2, second 2. For 5, (5+1)//2 is 3, so first part is 3, second is 2. Yes that's correct.",
 'So the split point is left_length = (len(s) +1)//2, then right_length = len(s) - left_length.',
 'Once the string is split into left and right parts, swapping them gives the right part followed by left part. The concatenation of right + left should equal the sorted string of the original.',
 "Wait, so the process is: original = s\nsorted_s = sorted(s, key=lambda c: ord(c))\nswapped = right + left\nthen check if swapped equals sorted_s.\nWait that's the key equation: swapped (after splitting and swapping the two halves) should equal the sorted string.\nSo, the steps are:\nFunction IsHalfSort(s):\n1. If the string is empty: Return True (since the swapped would be empty, and sorted as well).",
 '2. Split s into left and right. Left has length (n+1)//2, right is the remaining.\n3. swapped = right + left\n4. sorted_s = sorted(s)  (since sorted(s) sorts by codepoints, which is what we need)\n5. return swapped == sorted_s',
 'Wait, yes. So this is straightforward. But I need to make sure that the splitting is done correctly.',
 'Let me test the example "node" again. "node" is length 4. left length is (4+1)/2 = 2.5 floored?',
 "Wait in Python (if coding in Python), (4 +1)//2 is 2 (since integer division in Python uses floor?), wait 5//2 is 2 in integer division. So the left is first 2 characters: 'no', the right is next 2 'de'.",
 "So swapping gives 'de' + 'no' → 'deno' which is sorted. So it works.",
 "Another example: 'rum' is a True case. Let's see:\nOriginal: 'r', 'u', 'm'",
 'sorted would be [\'m\',\'r\',\'u\']\nsplit: length 3, (3+1)//2 is 2. So left is first 2 letters: \'ru\', right \'m\'\nswap gives \'m\' + \'ru\' → \'mur\'.\nCompare with sorted([\'r\',\'u\',\'m\']) → [\'m\',\'r\',\'u\'] which is \'mur\'.\nSo yes, so it returns true. Wait \'sorted(rum) is m r u → "mur"?\nWait the sorted \'rum\' would be \'m\',\'r\',\'u\' → "mur".\nSo the swapped string after split is \'m\'+\'ru\' → \'mur\' which equals the sorted string. So yes, correct.\nAnother test case: \'aaa\' → True. Since splitting into first (3+1)//2 = 2 characters, so left is \'aa\', right \'a\'.\nswapping gives a+aa → \'aaa\', which matches the sorted (already sorted) version.',
 "Now for the test case 'deno' which returns false. original is deno. Let's see, sorted should be the sorted of 'd e n o' which is d, e, n, o → which is 'deno'.",
 "But when split into halves: since len is 4, left is first 2 (de?), right is next 2 (no).\nswapping gives 'no' + 'de' → 'node'.",
 "So the swapped is 'node', which has to be compared to the sorted (original deno is already sorted?), but original here is deno, which sorted is the same. Wait wait. Wait in the test case, 'deno' is supposed to return False. The problem says deno is false. Let me think why.",
 "Ah, the problem states that 'node' is a half-sort, so after swapping halves gives the sorted. But in the case of 'deno', splitting the string (assuming the original is deno) into left (de) and right (no), swapping gives 'no'+'de' → node again. The sorted version of 'deno' is 'deno' itself (because the characters are already in order).",
 "So the swapped would be 'node' which isn't equal to the sorted string (which is deno), so deno returns false. That makes sense.",
 'So the logic here is correct.',
 'Now, to code this.',
 "So first, in Python, the steps would be:\ndef is_half_sort(s):\nn = len(s)\nif n ==0: return True # compute split point\n```python\nleft_len = (n +1 ) //2\n\nleft = s[:left_len]\n\nright = s[left_len:]\n\nswapped = right + left\n\nsorted_s = ''.join(sorted(s))\n\nreturn swapped == sorted_s\n```",
 "Wait, yes. Let's check the examples.",
 'Test case "node" → swapped is right (characters at index 2-3: \'d\' and \'e\', so \'de\'? Wait, original s is \'node\', so s[0:2] is \'no\', and right is the rest, \'de\'? then right + left would be \'de\'+\'no\' → \'deno\', which is sorted. So the function returns True. "rum" → \'r\', \'u\', \'m\' → split into first 2 ( \'ru\' and \'m\'), swapped is \'m\'+\'ru\' → \'mur\', which is the sorted version. So returns True. \'deno\' → the code\'s sorted(s) is deno, but swapped is right (s[2:] is \'no\') and left is first 2 \'de\' → swapped is \'no\'+\'de\' → node, which is not equal to deno. So returns False → which matches.',
 "Another test case: 'aaa' → split into left of 2 (aa) and right 'a'. swapped is 'a'+'aa' → 'aaa', which equals the sorted (same as original). So yes.",
 "Now the edge cases:\nTest string of length 1:\ns = 'a' → left length (1+1)/2 =1, so right is empty. swapped is '' + 'a' → 'a', which equals sorted_s → True.",
 "Length 2: 'ab'. split into first 1 +1//2 → (2+1)//2 =1.5 → 1. So left is 'a', right 'b'. swapped is 'ba'. sorted is 'ab' → so if 'ba' vs sorted(s) 'ab', then only if the original is 'ba'? Let's check. For s='ba': split into first 1 (left is 'b'), right is 'a', swapped becomes 'a' + 'b' → 'ab', which is sorted. So the function returns True for 'ba'?",
 "Wait yes. The function would say 'ba' is a half-sort. Because swapping halves gives 'ab', which is the sorted version. So 'ba' would return True.",
 "Wait the problem's examples don't include this, but according to the definition, that should be the case.",
 'Wait let\'s think: for "ba", the sorted is "ab", which is exactly the swapped parts (swap the two halves \'b\' and \'a\') → yes.',
 'Therefore the function is correct here.',
 'Another test case: "ba" → returns True.\nWait the problem\'s sample test case \'deno\' → the sorted is same as original, but the swapped gives node which is different. So returns False. Correct.',
 "Another case 'ab' → sorted is ab. split into a and b → swapping gives ba. So 'ab' would give swapped 'ba', which is different from sorted (ab). So function returns False. So 'ab' is not a half-sort, but 'ba' is. That's correct.",
 'So the code seems correct.',
 "Wait what about 'aab' (length 3):\nLet's see. The split: (3+1)//2 = 2. Left is first 2 characters, 'aa', right 'b'. swapping gives 'b' + 'aa' → 'baa'. sorted(s) would be 'aab' → so the sorted is 'aab'? No, sorted('aab') would be 'aab' sorted by characters. Since the codepoints for a are same, so the sorted is same as the original. So the swapped 'baa' would not equal the sorted 'aab', so function returns False.",
 "Wait, but the actual sorted of 'aab' is 'aab'? Yes. The original is 'aab', which when split into left 'aa' and right 'b', then swapped is 'b' + 'aa' → 'baa', which is not sorted, so the function returns False. So that works.",
 "Another example where it works: let's take 'cba' (len 3). Then left is (3+1)//2 =2, so left is first two characters: 'cb' → and the right is 'a'. swapping gives 'a' + 'cb' → 'acb'. The sorted of 'cba' would be 'abc'. So 'acb' is not equal to 'abc', so function returns False.",
 "Hmm. Suppose we have a string where the halves, when swapped, give the sorted version. Let's see another example. Let's take a 5-length string.",
 "Suppose the string is 'badce'. Wait, maybe think of another example where it works.",
 "Wait, perhaps 'bcdefa' with some split? Hmm not sure, let me think of a small example. Let's think of 'race'.",
 "Original string 'race' → length 4.",
 "Split into 'ra' (first 2), 'ce' → swapped → 'ce ra'.\nso swapped is 'cer' → no, wait 'ce' concatenated with 'ra' → 'cer a' → 'cer' is not right. Wait wait 'race' split into first 2 letters: 'ra' and 'ce'. Swapped is 'ce'+'ra' → 'cera'.",
 "Now sorted('race') → sorted as a e c r → code points of 'a' (97), 'c'(99), 'e'(101), 'r'(114). So sorted is 'a c e r' → 'acer', but swapped gives 'cera', which isn't equal. So this is not a half-sort.",
 "Wait, but if we have the original string as 'cera', then sorted would be 'acer' which is the swapped of 'cera' split into first two and second. So in that case the original string is 'cera'?",
 'Hmm, complicating further. Well, the code seems okay as per the examples given.',
 'Therefore, the code should work. Now I need to code that in Python, and handle all cases.',
 'Wait, what about when the string is of even length? The code should correctly split into two halves.',
 'So the code is:\n```python\ndef is_half_sort(s):\n\n    n = len(s)\n\n    # Split the string into left and right parts.\n\n    split_at = (n + 1) // 2  # because first half can be longer by one\n\n    left = s[:split_at]\n\n    right = s[split_at:]\n\n    swapped = right + left\n\n    # Now compare swapped to the sorted version of the original string.\n\n    return swapped == \'\'.join(sorted(s))\n\nYes.\n\nNow check the test cases:\n\nFor \'node\' → returns True.\n\nFor \'rum\' → returns True.\n\nFor \'aaa\' → True.\n\nFor \'deno\' → returns False.\n\nFor \'rim\' → let\'s see:\n\nOriginal \'rim\', length 3. Split into first 2: \'ri\', right \'m\'.\n\nswapped is \'m\' + \'ri\' → \'mri\'.\n```\nsorted(\'rim\') → the characters \'i\'(105), \'m\'(109), \'r\'(114) → sorted would be \'imr\' → "imr".\nSo \'mri\' vs \'imr\' → not equal, so returns False. Which matches the test case.\nAnother test case \'aaa\' → returns True as above. Edge Cases:\nTest case length 0 → returns True.\nTest case with length 2: \'ba\' → returns True because swapping gives \'ab\' which is the sorted.',
 'So the function works for these.',
 'So this should be the solution.']

## Correspondence of summaries and sentences

In [20]:
print(om_ds[0]['blocks'])
print(len(om_ds[0]['blocks']))

[[0, 4], [5, 17], [18, 29], [30, 34], [35, 42], [43, 54], [55, 59]]
7

In [21]:
print(om_ds[0]['block_summaries'])
print(len(om_ds[0]['block_summaries']))

['Clarifies definition of half-sort: split string into two halves (first half longer if length odd), swap halves; if swapped string equals the sorted string (by ASCII/codepoints), input is considered half-sort. Verifies example "node": length 4 -> split "no" | "de", swap -> "deno", which matches sorted("node") = "deno".', "Plans function to check property. Handles small lengths: length 0 and 1 considered half-sort (length 1: split as first half 1 char, second empty; swap unchanged; sorted equals original). For general length n: define left_len = (len(s)+1)//2, right_len = len(s) - left_len; left = s[:left_len], right = s[left_len:], swapped = right + left; sorted_s = ''.join(sorted(s)); return swapped == sorted_s. Sorting uses default order (ASCII/codepoints).", 'Defines split rule: left_len = (n+1)//2; left = s[:left_len]; right = s[left_len:]; half-sort test is right+left == \'\'.join(sorted(s)). Applies rule to examples: node -> left "no", right "de", swapped "deno" equals sorted "deno"; rum -> left "ru", right "m", swapped "mur" equals sorted "mur"; aaa -> left "aa", right "a", swapped "aaa" equals sorted "aaa"; deno -> left "de", right "no", swapped "node" != sorted "deno". Concludes method matches expected outcomes.', 'Writes Python-style implementation: def is_half_sort(s): n = len(s); if n == 0: return True; left_len = (n+1)//2; left = s[:left_len]; right = s[left_len:]; swapped = right + left; sorted_s = \'\'.join(sorted(s)); return swapped == sorted_s. Re-checks examples "node", "rum", "deno", "aaa" and confirms outputs match expectations.', 'Examines edge cases. Length 1: "a" -> left_len = (1+1)//2 = 1, right empty; swapped "a"; sorted "a" => True. Length 2: split index = (2+1)//2 = 1; for "ba": left "b", right "a", swapped "ab", sorted "ab" => True; for "ab": left "a", right "b", swapped "ba", sorted "ab" => False. Concludes behavior for length-2 strings is consistent with the definition.', 'Uses the definition/criterion: let n=len(s), mid=(n+1)//2, left=s[0:mid], right=s[mid:], and s is a half-sort iff right+left == \'\'.join(sorted(s)). Applies this via manual case analysis / spot-checking: for "aab" (n=3) -> mid=2, left="aa", right="b", swapped="baa", sorted("aab")="aab" => not equal, so False; for "cba" (n=3) -> left="cb", right="a", swapped="acb", sorted("cba")="abc" => False. Tries to construct an example that satisfies the criterion, explores length-4 "race": split into "ra" and "ce", swapped="cera", sorted("race")="acer" => not equal, so False. Then speculates that perhaps "cera" itself might be such an example but does not verify this. Concludes informally that the code appears correct for these checked cases, with odd-length split rule mid=(len(s)+1)//2 (left longer when odd) being used consistently.', 'Presents final Python solution (without explicit empty-string special case this time): def is_half_sort(s): n = len(s); split_at = (n+1)//2; left = s[:split_at]; right = s[split_at:]; swapped = right + left; return swapped == \'\'.join(sorted(s)). Re-validates given tests: "node" True, "rum" True, "aaa" True, "deno" False, "rim" False (since swapped "mri" vs sorted "imr"), empty string True (because both swapped and sorted are ""), "ba" True. Concludes this function is the intended solution.']
7

In [22]:
len(om_ds[0]['sentences'])

60

In [23]:
data = om_ds[0]

In [24]:
data['sentences'][data['blocks'][0][0] : data['blocks'][0][1]]

["Okay, so I need to figure out how to determine if a given string is a half-sort. Hmm, let's start by understanding the problem again. The half-sort is when if you split the string into two equal halves (with the first half being longer if the length is odd), then swap those two halves, the result should be the same as sorting the original string. Oh right, and splitting for odd-length means the first half is longer.",
 'Let me rephrase the example given. Take the string "node".',
 'The original characters are n, o, d, e. When sorted by their ASCII codes, they become d, e, n, o. Which is "deno".',
 'Now, splitting "node" into two halves: since it\'s 4 characters, each half is 2. The first half is \'no\' and the second is \'de\'.']

In [25]:
len(data['block_summaries'][0])

319

## Evaluating summaries

## Loading model

In [27]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

MODEL_ID = "Qwen/Qwen3-1.7B"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=dtype,
    trust_remote_code=True,
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

def ask_qwen(prompt, max_new_tokens=256, temperature=0.7):
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(text, return_tensors="pt").to(device)

    generation_kwargs = {
        "max_new_tokens": max_new_tokens,
        "do_sample": temperature > 0,
        "pad_token_id": tokenizer.eos_token_id,
    }
    if temperature > 0:
        generation_kwargs["temperature"] = temperature

    with torch.no_grad():
        output = model.generate(
            **inputs,
            **generation_kwargs,
        )

    generated_tokens = output[0][inputs["input_ids"].shape[1]:]
    return tokenizer.decode(generated_tokens, skip_special_tokens=True)

print(f"Loaded {MODEL_ID} on {device} with dtype={dtype}")

/home/jennifer/scratch/micromamba/envs/info/lib/python3.12/site-packages/torch/cuda/__init__.py:180: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Fetching 2 files: 100%|██████████| 2/2 [00:14<00:00,  7.26s/it]
Loading weights: 100%|██████████| 311/311 [00:04<00:00, 66.50it/s]

Loaded Qwen/Qwen3-1.7B on cpu with dtype=torch.float32

In [28]:
import torch

def token_logits(text):
    inputs = tokenizer(text, return_tensors="pt").to(device)
    with torch.no_grad():
        logits = model(**inputs).logits

    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    return tokens, logits[0]  # shape: [seq_len, vocab_size]

tokens, logits = token_logits("Hello, World")
print(tokens)
print(logits.shape)

['Hello', ',', 'ĠWorld']
torch.Size([3, 151936])

The Ġ is just a marker for “there was a space before this token.”

In [29]:
logits.shape

torch.Size([3, 151936])

In [30]:
def next_token_scores(text):
    inputs = tokenizer(text, return_tensors="pt").to(device)
    with torch.no_grad():
        logits = model(**inputs).logits[0]

    input_ids = inputs["input_ids"][0]
    tokens = tokenizer.convert_ids_to_tokens(input_ids)

    next_logits = logits[:-1]          # predicts token 1..n-1
    next_token_ids = input_ids[1:]     # actual tokens 1..n-1
    actual_token_logits = next_logits.gather(
        1, next_token_ids.unsqueeze(1)
    ).squeeze(1)

    return tokens[1:], actual_token_logits

tokens, scores = next_token_scores("Hello world")
for tok, score in zip(tokens, scores.tolist()):
    print(tok, score)

Ġworld 1.3933730125427246

In [31]:
import pandas as pd
import torch.nn.functional as F

row = om_ds[0]
block_start, block_end = row["blocks"][0]

summary_text = row["block_summaries"][0]
relevant_text = " ".join(row["sentences"][block_start:block_end + 1])

def token_score_table(text, label):
    inputs = tokenizer(text, return_tensors="pt").to(device)
    with torch.no_grad():
        logits = model(**inputs).logits[0]

    input_ids = inputs["input_ids"][0]
    tokens = tokenizer.convert_ids_to_tokens(input_ids)
    next_logits = logits[:-1]
    next_token_ids = input_ids[1:]
    next_tokens = tokenizer.convert_ids_to_tokens(next_token_ids)

    actual_token_logits = next_logits.gather(1, next_token_ids.unsqueeze(1)).squeeze(1)
    log_probs = F.log_softmax(next_logits, dim=-1)
    actual_token_logprobs = log_probs.gather(1, next_token_ids.unsqueeze(1)).squeeze(1)

    return pd.DataFrame({
        "text_label": label,
        "context_token": tokens[:-1],
        "predicted_token": next_tokens,
        "actual_token_logit": actual_token_logits.detach().cpu().tolist(),
        "actual_token_logprob": actual_token_logprobs.detach().cpu().tolist(),
    })

summary_scores = token_score_table(summary_text, "summary_block_0")
relevant_scores = token_score_table(relevant_text, "relevant_sentences_0_4")

comparison = pd.DataFrame([
    {
        "text_label": "summary_block_0",
        "num_chars": len(summary_text),
        "num_tokens": len(summary_scores),
        "mean_actual_token_logit": summary_scores["actual_token_logit"].mean(),
        "mean_actual_token_logprob": summary_scores["actual_token_logprob"].mean(),
    },
    {
        "text_label": "relevant_sentences_0_4",
        "num_chars": len(relevant_text),
        "num_tokens": len(relevant_scores),
        "mean_actual_token_logit": relevant_scores["actual_token_logit"].mean(),
        "mean_actual_token_logprob": relevant_scores["actual_token_logprob"].mean(),
    },
])

print("First summary block:\n", summary_text, "\n", sep="")
print("Relevant sentences:\n", relevant_text, "\n", sep="")
comparison

First summary block:
Clarifies definition of half-sort: split string into two halves (first half longer if length odd), swap halves; if swapped string equals the sorted string (by ASCII/codepoints), input is considered half-sort. Verifies example "node": length 4 -> split "no" | "de", swap -> "deno", which matches sorted("node") = "deno".

Relevant sentences:
Okay, so I need to figure out how to determine if a given string is a half-sort. Hmm, let's start by understanding the problem again. The half-sort is when if you split the string into two equal halves (with the first half being longer if the length is odd), then swap those two halves, the result should be the same as sorting the original string. Oh right, and splitting for odd-length means the first half is longer. Let me rephrase the example given. Take the string "node". The original characters are n, o, d, e. When sorted by their ASCII codes, they become d, e, n, o. Which is "deno". Now, splitting "node" into two halves: since it's 4 characters, each half is 2. The first half is 'no' and the second is 'de'. Swapping gives 'deno', which matches the sorted version. So that's why it's a half-sort.

,text_label,num_chars,num_tokens,mean_actual_token_logit,mean_actual_token_logprob
0,summary_block_0,319,76,23.604156,-3.745724
1,relevant_sentences_0_4,809,199,29.785561,-1.740183

In [32]:
import torch.nn.functional as F

def get_final_logits(text):
    inputs = tokenizer(text, return_tensors="pt").to(device)
    with torch.no_grad():
        return model(**inputs).logits[0, -1]  # [vocab_size]

sentences_logits = get_final_logits(relevant_text)
summary_logits   = get_final_logits(summary_text)

sentences_probs     = F.softmax(sentences_logits,     dim=-1)
summary_probs       = F.softmax(summary_logits,       dim=-1)
sentences_log_probs = F.log_softmax(sentences_logits, dim=-1)
summary_log_probs   = F.log_softmax(summary_logits,   dim=-1)

kl_summ_sent = F.kl_div(sentences_log_probs, summary_probs,   reduction="sum")
kl_sent_summ = F.kl_div(summary_log_probs,   sentences_probs, reduction="sum")

print(f"KL(future|summary   || future|sentences) = {kl_summ_sent.item():.4f}")
print(f"KL(future|sentences || future|summary)   = {kl_sent_summ.item():.4f}")

KL(future|summary   || future|sentences) = 3.7878
KL(future|sentences || future|summary)   = 1.8838

In [33]:
block1_start, block1_end = row["blocks"][1]
next_block_text = " ".join(row["sentences"][block1_start:block1_end + 1])

def continuation_logprobs(prefix_text, continuation_text):
    """Per-token log-probs of continuation tokens conditioned on prefix."""
    full_text = prefix_text + " " + continuation_text
    full_inputs = tokenizer(full_text, return_tensors="pt").to(device)
    prefix_len  = tokenizer(prefix_text, return_tensors="pt")["input_ids"].shape[1]

    with torch.no_grad():
        logits = model(**full_inputs).logits[0]  # [seq_len, vocab_size]

    full_ids   = full_inputs["input_ids"][0]
    # logits[i] predicts token i+1; slice so we predict the continuation tokens
    cont_logits = logits[prefix_len - 1 : -1]
    cont_ids    = full_ids[prefix_len:]

    log_probs       = F.log_softmax(cont_logits, dim=-1)
    token_logprobs  = log_probs.gather(1, cont_ids.unsqueeze(1)).squeeze(1)
    cont_tokens     = tokenizer.convert_ids_to_tokens(cont_ids)
    return cont_tokens, token_logprobs

tokens_sent, lp_sent = continuation_logprobs(relevant_text, next_block_text)
tokens_summ, lp_summ = continuation_logprobs(summary_text,  next_block_text)

print(f"blocks[1] | sentences prefix:  mean log-prob = {lp_sent.mean().item():.4f}  perplexity = {torch.exp(-lp_sent.mean()).item():.2f}")
print(f"blocks[1] | summary  prefix:   mean log-prob = {lp_summ.mean().item():.4f}  perplexity = {torch.exp(-lp_summ.mean()).item():.2f}")

blocks[1] | sentences prefix:  mean log-prob = -1.4208  perplexity = 4.14
blocks[1] | summary  prefix:   mean log-prob = -1.4317  perplexity = 4.19

In [38]:
results = []

for i in range(len(row["blocks"]) - 1):
    s, e   = row["blocks"][i]
    s1, e1 = row["blocks"][i + 1]

    prefix_sentences = " ".join(row["sentences"][s  : e  + 1])
    prefix_summary   = row["block_summaries"][i]
    next_block_text  = " ".join(row["sentences"][s1 : e1 + 1])

    _, lp_sent = continuation_logprobs(prefix_sentences, next_block_text)
    _, lp_summ = continuation_logprobs(prefix_summary,   next_block_text)

    results.append({
        "block": i,
        "next_block_text": next_block_text,
        "n_tokens_next": len(lp_sent),
        "mean_logprob_sentences": lp_sent.mean().item(),
        "mean_logprob_summary":   lp_summ.mean().item(),
        "perplexity_sentences":   torch.exp(-lp_sent.mean()).item(),
        "perplexity_summary":     torch.exp(-lp_summ.mean()).item(),
    })

df = pd.DataFrame(results)
df["perplexity_delta"] = df["perplexity_summary"] - df["perplexity_sentences"]
df

,block,next_block_text,n_tokens_next,mean_logprob_sentences,mean_logprob_summary,perplexity_sentences,perplexity_summary,perplexity_delta
0,0,The task is to write a function that checks if...,737,-1.420779,-1.431666,4.140343,4.185669,0.045326
1,1,"Wait, yes. So this is straightforward. But I n...",654,-1.809691,-1.778868,6.108558,5.923147,-0.185410
2,2,"Now, to code this. So first, in Python, the st...",342,-1.512333,-1.627989,4.537303,5.093619,0.556316
3,3,Now the edge cases:\nTest string of length 1:\...,385,-1.650797,-1.824287,5.211132,6.198376,0.987244
4,4,So the code seems correct. Wait what about 'aa...,604,-1.541816,-1.701007,4.673069,5.479463,0.806394
5,5,"Therefore, the code should work. Now I need to...",357,-1.724354,-1.790175,5.608898,5.990499,0.381600

## Running context: cumulative sentences vs cumulative summaries

In [42]:
running_results = []

for i in range(len(row["blocks"]) - 1):
    s1, e1 = row["blocks"][i + 1]
    next_block_text = " ".join(row["sentences"][s1 : e1 + 1])

    # cumulative sentences: all sentences from blocks 0..i
    s0, _ = row["blocks"][0]
    _, ei  = row["blocks"][i]
    running_sentences = " ".join(row["sentences"][s0 : ei + 1])

    # cumulative summaries: all summaries from blocks 0..i
    running_summary = " ".join(row["block_summaries"][: i + 1])

    _, lp_sent = continuation_logprobs(running_sentences, next_block_text)
    _, lp_summ = continuation_logprobs(running_summary,   next_block_text)

    running_results.append({
        "block": i,
        "next_block_text": next_block_text,
        "n_tokens_next": len(lp_sent),
        "mean_logprob_sentences": lp_sent.mean().item(),
        "mean_logprob_summary":   lp_summ.mean().item(),
        "perplexity_sentences":   torch.exp(-lp_sent.mean()).item(),
        "perplexity_summary":     torch.exp(-lp_summ.mean()).item(),
    })

df_running = pd.DataFrame(running_results)
df_running["perplexity_delta"] = df_running["perplexity_summary"] - df_running["perplexity_sentences"]
df_running

,block,next_block_text,n_tokens_next,mean_logprob_sentences,mean_logprob_summary,perplexity_sentences,perplexity_summary,perplexity_delta
0,0,The task is to write a function that checks if...,737,-1.420779,-1.431666,4.140343,4.185669,0.045326
1,1,"Wait, yes. So this is straightforward. But I n...",654,-1.754671,-1.771512,5.781547,5.879739,0.098192
2,2,"Now, to code this. So first, in Python, the st...",342,-1.423376,-1.617416,4.151110,5.040048,0.888938
3,3,Now the edge cases:\nTest string of length 1:\...,385,-1.543382,-1.731914,4.680391,5.651462,0.971071
4,4,So the code seems correct. Wait what about 'aa...,604,-1.441431,-1.625928,4.226741,5.083133,0.856392
5,5,"Therefore, the code should work. Now I need to...",357,-1.338071,-1.509230,3.811683,4.523247,0.711565

In [43]:
def generate_continuation(prefix_text, max_new_tokens=150):
    inputs = tokenizer(prefix_text, return_tensors="pt").to(device)
    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,          # greedy — deterministic
            pad_token_id=tokenizer.eos_token_id,
        )
    new_tokens = output[0][inputs["input_ids"].shape[1]:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True)


SEP = "-" * 80

for i in range(len(row["blocks"]) - 1):
    s,  e  = row["blocks"][i]
    s1, e1 = row["blocks"][i + 1]

    prefix_sentences = " ".join(row["sentences"][s  : e  + 1])
    prefix_summary   = row["block_summaries"][i]
    actual_next      = " ".join(row["sentences"][s1 : e1 + 1])

    gen_from_sentences = generate_continuation(prefix_sentences)
    gen_from_summary   = generate_continuation(prefix_summary)

    print(f"\n{'=' * 80}")
    print(f"BLOCK {i} → predicting block {i+1}")
    print(f"{SEP}\nACTUAL next block:\n{actual_next}")
    print(f"{SEP}\nGENERATED from sentences:\n{gen_from_sentences}")
    print(f"{SEP}\nGENERATED from summary:\n{gen_from_summary}")

[transformers] The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

================================================================================
BLOCK 0 → predicting block 1
--------------------------------------------------------------------------------
ACTUAL next block:
The task is to write a function that checks if a given string satisfies this condition. So the steps I need to do are:
1. Check the length of the string. If it's 0 or 1, maybe it's trivially half-sort? Wait, if length is 1, then splitting into halves would just have the first half as the entire string and the second as empty? Or maybe according to the specs, for odd length, first half is longer. So length 1 would be first half (1 char), second half none?
So swapping would mean moving the second (empty) to front and first part to end, but that would be the same?
Hmm, but let's see. Maybe for length 1, the split is first half (1), second half (0). Swapping them gives the original string. Then the sorted version must also be the original. So only if the string is already sorted, which a single character is. So for length 1, it would return True. 2. For the general case:
- Split the string into two parts: left and right. The split point is at (length + 1) // 2 for the first part. Because for odd length, first part is longer by one. Wait, for example, when the string length is 5, split at (5+1)/2 = 3, so first part is 3, second 2. Correct. So for n even length like 4, the split is (4 +1)/2? Wait wait, 4 is even, so (4 +1)//2 would be 2.5 rounded down?
Wait, (4+1) is 5 divided by 2 is 2.5. Using integer division, 5//2 is 2. So split at 2 and 2. That makes sense.
Wait no. Wait, (length +1 )//2 gives the split point for the first part. So for length 4, (4+1)//2 is 2.5? No, (4+1) is 5 divided by 2, integer division is 2. Wait, 5 divided by 2 is 2 with remainder 1, so yes, 2. So the first part is 2, second 2. For 5, (5+1)//2 is 3, so first part is 3, second is 2. Yes that's correct. So the split point is left_length = (len(s) +1)//2, then right_length = len(s) - left_length. Once the string is split into left and right parts, swapping them gives the right part followed by left part. The concatenation of right + left should equal the sorted string of the original. Wait, so the process is: original = s
sorted_s = sorted(s, key=lambda c: ord(c))
swapped = right + left
then check if swapped equals sorted_s.
Wait that's the key equation: swapped (after splitting and swapping the two halves) should equal the sorted string.
So, the steps are:
Function IsHalfSort(s):
1. If the string is empty: Return True (since the swapped would be empty, and sorted as well). 2. Split s into left and right. Left has length (n+1)//2, right is the remaining.
3. swapped = right + left
4. sorted_s = sorted(s)  (since sorted(s) sorts by codepoints, which is what we need)
5. return swapped == sorted_s
--------------------------------------------------------------------------------
GENERATED from sentences:


So the task is to check if a given string is a half-sort. Let's think about the steps needed.

First, the string must be even-length or odd-length. For even-length strings, split into two equal parts. For odd-length, split into first (n//2 + 1) characters and the rest. Then, swap the two halves. Then, check if the resulting string is the same as the sorted string.

Wait, but how do we handle the sorting? For example, if the string is "abc", which is length 3. Split into first 2 characters "ab" and "c". Swap them to get "ca". Then sort "ca" which is "ac". So the original
--------------------------------------------------------------------------------
GENERATED from summary:
 So "node" is half-sort. But "node" is not a half-sort in the original problem's definition. Wait, why? Because the original problem says "sorted by ASCII codepoints", which is the same as the sorted string. So "node" is half-sort. But the original problem says that "node" is not half-sort. So there's a contradiction here. Wait, maybe I misunderstood the original problem. Let me check again.

Original problem: "node" is not half-sort. But according to the definition, it should be. So there must be a misunderstanding. Let me re-examine the problem.

The original problem says: "node" is not half-sort. But according to the definition, it should be

================================================================================
BLOCK 1 → predicting block 2
--------------------------------------------------------------------------------
ACTUAL next block:
Wait, yes. So this is straightforward. But I need to make sure that the splitting is done correctly. Let me test the example "node" again. "node" is length 4. left length is (4+1)/2 = 2.5 floored? Wait in Python (if coding in Python), (4 +1)//2 is 2 (since integer division in Python uses floor?), wait 5//2 is 2 in integer division. So the left is first 2 characters: 'no', the right is next 2 'de'. So swapping gives 'de' + 'no' → 'deno' which is sorted. So it works. Another example: 'rum' is a True case. Let's see:
Original: 'r', 'u', 'm' sorted would be ['m','r','u']
split: length 3, (3+1)//2 is 2. So left is first 2 letters: 'ru', right 'm'
swap gives 'm' + 'ru' → 'mur'.
Compare with sorted(['r','u','m']) → ['m','r','u'] which is 'mur'.
So yes, so it returns true. Wait 'sorted(rum) is m r u → "mur"?
Wait the sorted 'rum' would be 'm','r','u' → "mur".
So the swapped string after split is 'm'+'ru' → 'mur' which equals the sorted string. So yes, correct.
Another test case: 'aaa' → True. Since splitting into first (3+1)//2 = 2 characters, so left is 'aa', right 'a'.
swapping gives a+aa → 'aaa', which matches the sorted (already sorted) version. Now for the test case 'deno' which returns false. original is deno. Let's see, sorted should be the sorted of 'd e n o' which is d, e, n, o → which is 'deno'. But when split into halves: since len is 4, left is first 2 (de?), right is next 2 (no).
swapping gives 'no' + 'de' → 'node'. So the swapped is 'node', which has to be compared to the sorted (original deno is already sorted?), but original here is deno, which sorted is the same. Wait wait. Wait in the test case, 'deno' is supposed to return False. The problem says deno is false. Let me think why. Ah, the problem states that 'node' is a half-sort, so after swapping halves gives the sorted. But in the case of 'deno', splitting the string (assuming the original is deno) into left (de) and right (no), swapping gives 'no'+'de' → node again. The sorted version of 'deno' is 'deno' itself (because the characters are already in order). So the swapped would be 'node' which isn't equal to the sorted string (which is deno), so deno returns false. That makes sense. So the logic here is correct.
--------------------------------------------------------------------------------
GENERATED from sentences:


Wait, but sorted(s) is a list, and swapped is a string. So we need to compare the string representations. So for example, if s is "abc", sorted_s is ["a", "b", "c"], and swapped is "bc" + "a" = "bca". Which is not equal to "abc", so returns False. But if s is "acb", then sorted_s is "abc", swapped is "bc" + "a" = "bca" which is not equal. So the function would return False. But what about "ab"? The sorted is "ab", swapped is "ba" which is not equal. So returns False. But for "a", the sorted is "
--------------------------------------------------------------------------------
GENERATED from summary:
 This is a bit of a hack, but it's the best I can think of for the given constraints. The code is written in Python, and the function is called 'functions' with the parameter 's'. The code is written in a way that it's not using any external libraries, just the standard ones. The code is written in a way that it's not using any built-in functions that would make it too efficient, but it's acceptable for the problem's constraints. The code is written in a way that it's not using any other functions that would make it too slow, but it's acceptable for the problem's constraints. The code is written in a way that it's not using any other functions that would make it too slow

================================================================================
BLOCK 2 → predicting block 3
--------------------------------------------------------------------------------
ACTUAL next block:
Now, to code this. So first, in Python, the steps would be:
def is_half_sort(s):
n = len(s)
if n ==0: return True # compute split point
```python
left_len = (n +1 ) //2

left = s[:left_len]

right = s[left_len:]

swapped = right + left

sorted_s = ''.join(sorted(s))

return swapped == sorted_s
``` Wait, yes. Let's check the examples. Test case "node" → swapped is right (characters at index 2-3: 'd' and 'e', so 'de'? Wait, original s is 'node', so s[0:2] is 'no', and right is the rest, 'de'? then right + left would be 'de'+'no' → 'deno', which is sorted. So the function returns True. "rum" → 'r', 'u', 'm' → split into first 2 ( 'ru' and 'm'), swapped is 'm'+'ru' → 'mur', which is the sorted version. So returns True. 'deno' → the code's sorted(s) is deno, but swapped is right (s[2:] is 'no') and left is first 2 'de' → swapped is 'no'+'de' → node, which is not equal to deno. So returns False → which matches. Another test case: 'aaa' → split into left of 2 (aa) and right 'a'. swapped is 'a'+'aa' → 'aaa', which equals the sorted (same as original). So yes.
--------------------------------------------------------------------------------
GENERATED from sentences:
 So the algorithm is: for a string s, if the sorted version of s is equal to the string obtained by swapping the first half and the second half of s, then return True. So the code would be:

def is_half_sorted(s):
    if len(s) % 2 != 0:
        return False
    half = (len(s) + 1) // 2
    left = s[:half]
    right = s[half:]
    return sorted(s) == right + left

Wait, but in the case of even length, the split is (len(s) +1)//2. For example, len(s) = 4, (4+1)//2 = 2.5 floored
--------------------------------------------------------------------------------
GENERATED from summary:
 What is the correct answer for the input "deno"?

The input is "deno". The correct answer is "node". The reasoning process is as follows: the method of splitting the string into left and right parts, then swapping them, and comparing to the sorted string. For the input "deno", the left part is "de" and the right part is "no". Swapping them gives "node", which is the sorted version of "deno". Therefore, the correct answer is "node".
**Final Answer**
The correct answer is \boxed{node}.
The correct answer for the input "deno" is \boxed{node}.
The reasoning process is as follows: the method of splitting the string into left and right

================================================================================
BLOCK 3 → predicting block 4
--------------------------------------------------------------------------------
ACTUAL next block:
Now the edge cases:
Test string of length 1:
s = 'a' → left length (1+1)/2 =1, so right is empty. swapped is '' + 'a' → 'a', which equals sorted_s → True. Length 2: 'ab'. split into first 1 +1//2 → (2+1)//2 =1.5 → 1. So left is 'a', right 'b'. swapped is 'ba'. sorted is 'ab' → so if 'ba' vs sorted(s) 'ab', then only if the original is 'ba'? Let's check. For s='ba': split into first 1 (left is 'b'), right is 'a', swapped becomes 'a' + 'b' → 'ab', which is sorted. So the function returns True for 'ba'? Wait yes. The function would say 'ba' is a half-sort. Because swapping halves gives 'ab', which is the sorted version. So 'ba' would return True. Wait the problem's examples don't include this, but according to the definition, that should be the case. Wait let's think: for "ba", the sorted is "ab", which is exactly the swapped parts (swap the two halves 'b' and 'a') → yes. Therefore the function is correct here. Another test case: "ba" → returns True.
Wait the problem's sample test case 'deno' → the sorted is same as original, but the swapped gives node which is different. So returns False. Correct. Another case 'ab' → sorted is ab. split into a and b → swapping gives ba. So 'ab' would give swapped 'ba', which is different from sorted (ab). So function returns False. So 'ab' is not a half-sort, but 'ba' is. That's correct.
--------------------------------------------------------------------------------
GENERATED from sentences:
 So the code seems to work. But wait, the code is not correct for the case where the split is not the same as the sorted. For example, 'ab' → split into left 1, right 1. swapped is right + left → 'ba' which is sorted. So returns True. So the code seems to work. So the code is correct. So the code is as written. So the code is correct. So the answer is to write this function.
```python
def is_half_sort(s):
    n = len(s)
    if n == 0:
        return True
    left_len = (n + 1) // 2
    left = s[:left_len]
    right = s
--------------------------------------------------------------------------------
GENERATED from summary:
 Then, write a function that takes a string and returns the number of unique permutations of the string that are half-sorted. For example, for "node", the output is 2. How to approach this?

To solve this problem, we need to determine the number of unique permutations of a given string that are "half-sorted". A half-sorted string is defined as a string that can be split into two parts, where the second part is a sorted version of the first part. For example, "node" can be split into "no" and "de", and "de" is the sorted version of "no".

### Approach
1. **Understanding the Problem**: The task is to find the number of unique permutations of

================================================================================
BLOCK 4 → predicting block 5
--------------------------------------------------------------------------------
ACTUAL next block:
So the code seems correct. Wait what about 'aab' (length 3):
Let's see. The split: (3+1)//2 = 2. Left is first 2 characters, 'aa', right 'b'. swapping gives 'b' + 'aa' → 'baa'. sorted(s) would be 'aab' → so the sorted is 'aab'? No, sorted('aab') would be 'aab' sorted by characters. Since the codepoints for a are same, so the sorted is same as the original. So the swapped 'baa' would not equal the sorted 'aab', so function returns False. Wait, but the actual sorted of 'aab' is 'aab'? Yes. The original is 'aab', which when split into left 'aa' and right 'b', then swapped is 'b' + 'aa' → 'baa', which is not sorted, so the function returns False. So that works. Another example where it works: let's take 'cba' (len 3). Then left is (3+1)//2 =2, so left is first two characters: 'cb' → and the right is 'a'. swapping gives 'a' + 'cb' → 'acb'. The sorted of 'cba' would be 'abc'. So 'acb' is not equal to 'abc', so function returns False. Hmm. Suppose we have a string where the halves, when swapped, give the sorted version. Let's see another example. Let's take a 5-length string. Suppose the string is 'badce'. Wait, maybe think of another example where it works. Wait, perhaps 'bcdefa' with some split? Hmm not sure, let me think of a small example. Let's think of 'race'. Original string 'race' → length 4. Split into 'ra' (first 2), 'ce' → swapped → 'ce ra'.
so swapped is 'cer' → no, wait 'ce' concatenated with 'ra' → 'cer a' → 'cer' is not right. Wait wait 'race' split into first 2 letters: 'ra' and 'ce'. Swapped is 'ce'+'ra' → 'cera'. Now sorted('race') → sorted as a e c r → code points of 'a' (97), 'c'(99), 'e'(101), 'r'(114). So sorted is 'a c e r' → 'acer', but swapped gives 'cera', which isn't equal. So this is not a half-sort. Wait, but if we have the original string as 'cera', then sorted would be 'acer' which is the swapped of 'cera' split into first two and second. So in that case the original string is 'cera'? Hmm, complicating further. Well, the code seems okay as per the examples given.
--------------------------------------------------------------------------------
GENERATED from sentences:
 So the function is correct.

Now, the code. The code needs to take a string s, split into two halves, swap the two halves, and check if the result is the sorted version of s.

So, the steps:

1. Check if the length of s is even. If not, return False. Because the split into two halves is only possible if the length is even. For example, if the length is odd, the split would be (n+1)//2 and (n-1)//2. But the problem says that the string is split into two halves. So the code must handle even length. Wait, the problem says "split into two halves". So for even length, the split is into two equal parts
--------------------------------------------------------------------------------
GENERATED from summary:
 For length-3: split index = (3+1)//2 = 2; for "abc": left "ab", right "c", swapped "cba", sorted "cba" => True; for "acb": left "ac", right "b", swapped "ca b", sorted "acb" => False. So the algorithm works for length-3. So the algorithm seems to work for all cases. But wait, what about the case where the string is "ab" and the split index is 1, so left is "a", right is "b". Swapped is "ba", sorted is "ab" which is not equal to "ba". So the algorithm would return False, but the correct answer is True.

================================================================================
BLOCK 5 → predicting block 6
--------------------------------------------------------------------------------
ACTUAL next block:
Therefore, the code should work. Now I need to code that in Python, and handle all cases. Wait, what about when the string is of even length? The code should correctly split into two halves. So the code is:
```python
def is_half_sort(s):

    n = len(s)

    # Split the string into left and right parts.

    split_at = (n + 1) // 2  # because first half can be longer by one

    left = s[:split_at]

    right = s[split_at:]

    swapped = right + left

    # Now compare swapped to the sorted version of the original string.

    return swapped == ''.join(sorted(s))

Yes.

Now check the test cases:

For 'node' → returns True.

For 'rum' → returns True.

For 'aaa' → True.

For 'deno' → returns False.

For 'rim' → let's see:

Original 'rim', length 3. Split into first 2: 'ri', right 'm'.

swapped is 'm' + 'ri' → 'mri'.
```
sorted('rim') → the characters 'i'(105), 'm'(109), 'r'(114) → sorted would be 'imr' → "imr".
So 'mri' vs 'imr' → not equal, so returns False. Which matches the test case.
Another test case 'aaa' → returns True as above. Edge Cases:
Test case length 0 → returns True.
Test case with length 2: 'ba' → returns True because swapping gives 'ab' which is the sorted. So the function works for these. So this should be the solution.
--------------------------------------------------------------------------------
GENERATED from sentences:
 So the code is correct? Or maybe there's a mistake in the logic. Wait, the code is supposed to return True if the string is a half-sort, which means that when you split into two halves, and swap them, the result is the sorted string. So the code is checking if the sorted string is equal to the swapped string. So for the original string 'aab', the code would split into 'aa' and 'b', swap to 'baa', then check if sorted('aab') is 'aab' which is equal to 'baa'? No, so returns False. But the original string is 'aab', which is already sorted. So the code returns False, which is correct. Because the function is supposed to
--------------------------------------------------------------------------------
GENERATED from summary:
 So the code is correct.
The code is correct. The examples checked all satisfy the condition, and the logic is consistent with the definition. The code is correct.
The code is correct. The examples checked all satisfy the condition, and the logic is consistent with the definition. The code is correct.
The code is correct. The examples checked all satisfy the condition, and the logic is consistent with the definition. The code is correct.

In [44]:
summary_text

'Clarifies definition of half-sort: split string into two halves (first half longer if length odd), swap halves; if swapped string equals the sorted string (by ASCII/codepoints), input is considered half-sort. Verifies example "node": length 4 -> split "no" | "de", swap -> "deno", which matches sorted("node") = "deno".'

In [45]:
relevant_text

'Okay, so I need to figure out how to determine if a given string is a half-sort. Hmm, let\'s start by understanding the problem again. The half-sort is when if you split the string into two equal halves (with the first half being longer if the length is odd), then swap those two halves, the result should be the same as sorting the original string. Oh right, and splitting for odd-length means the first half is longer. Let me rephrase the example given. Take the string "node". The original characters are n, o, d, e. When sorted by their ASCII codes, they become d, e, n, o. Which is "deno". Now, splitting "node" into two halves: since it\'s 4 characters, each half is 2. The first half is \'no\' and the second is \'de\'. Swapping gives \'deno\', which matches the sorted version. So that\'s why it\'s a half-sort.'